command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
env:
  - name: PORT
    value: "8000"
  # Service Principal Authentication - Databricks automatically injects DATABRICKS_CLIENT_ID and DATABRICKS_CLIENT_SECRET
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  # Table configuration - can be overridden per environment via databricks.yml variables
  - name: "BACKEND_DATA_TABLE"
    value: "main.ashwinpo_bloomin.guestexperience_guestsentimentscore"
  - name: "EVALUATION_TABLE"
    value: "main.ashwinpo_bloomin.guestexperience_guestsentimentscore_evaluation"
  - name: "VECTOR_INDEX_NAME"
    value: "main.ashwinpo_bloomin.review_vector_index"
  - name: "EMBEDDING_MODEL_ENDPOINT_NAME"
    value: "databricks-gte-large-en"